#!/bin/bash --norc

LD_LIBRARY_PATH="${BAZEL_OUTPUT_ROOT}external/x86_64_clang_8_disco/usr/lib/x86_64-linux-gnu"
export LD_LIBRARY_PATH

exec -a x86_64-linux-gnueabihf-ar \
        ${BAZEL_OUTPUT_ROOT}external/x86_64_clang_8_disco/usr/bin/llvm-ar \
        "$@"
