[package]
name = "rnix"
version = "0.1.0"
authors = ["Jiahong Long <jiahong888long@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
bitflags = "1.0"

[dev-dependencies]
nix = "0.17.0"
