steps:
  - label: ":docker: Build"
    plugins:
      - docker-compose#v3.0.3:
            build: hyperion

  - label: ":docker: Test %n"
    command: bazel test //... --host_platform=bionic-linux-x86_64
    plugins:
      - docker-compose#v3.0.3:
          run: hyperion 
