steps:
  - label: ":docker: Build"
    plugins:
      - docker-compose#v3.0.3:
            build: hyperion

  - wait

  - label: ":docker: Test"
    command: ./bazel --bazelrc=.buildkite/.bazelrc test //... --host_platform=//tools/platforms:bionic-linux-x86_64
    plugins:
      - docker-compose#v3.0.3:
          run: hyperion
