steps:
  - label: ":docker: Build"
    plugins:
      - docker-login#v2.0.1:
            username: valkyrieregistry
            server: valkyrieregistry.azurecr.io
      - docker-compose#v3.0.3:
            build: hyperion_cached
            image-repository: valkyreregistry.azurecr.io

  - wait

  - label: ":docker: Test"
    command: bazel --bazelrc=.buildkite/.bazelrc test //... --host_platform=//tools/platforms:bionic-linux-x86_64
    plugins:
      - docker-login#v2.0.1:
            username: valkyrieregistry
            server: valkyrieregistry.azurecr.io
      - docker-compose#v3.0.3:
          run: hyperion_cached
          image-repository: valkyreregistry.azurecr.io
