#!/bin/bash --norc

LD_LIBRARY_PATH="${BAZEL_OUTPUT_ROOT}external/x86_64_clang_8_bionic/usr/lib/x86_64-linux-gnu"
LD_LIBRARY_PATH+=":${BAZEL_OUTPUT_ROOT}external/x86_64_clang_8_bionic/lib/x86_64-linux-gnu"
export LD_LIBRARY_PATH

exec \
    ${BAZEL_OUTPUT_ROOT}external/x86_64_clang_8_bionic/usr/bin/clang \
    "$@"
