#!/bin/bash --norc

LD_LIBRARY_PATH="${BAZEL_OUTPUT_ROOT}external/x86_64_clang_8/usr/lib/x86_64-linux-gnu"
LD_LIBRARY_PATH+=":${BAZEL_OUTPUT_ROOT}external/x86_64_clang_8/lib/x86_64-linux-gnu"

export LD_LIBRARY_PATH

exec \
    ${BAZEL_OUTPUT_ROOT}external/x86_64_clang_8/usr/bin/clang \
    "$@"
